# Why

I put together this repo in an attempt to replicate an issue I was seeing
with an application.

In particular, I was attempting to replicate this issue:

https://github.com/open-telemetry/opentelemetry-python/issues/2678

As of today, I've not been able to replicate in this repo or even in the application
where I initially found the issue.